# Generated by Django 5.2.8 on 2026-01-12 20:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('headhunter', 'HeadHunter'), ('habr_career', 'Habr Career'), ('superjob', 'SuperJob')], db_index=True, max_length=50, verbose_name='Источник')),
                ('parsing_mode', models.CharField(choices=[('api', 'API режим'), ('html', 'HTML режим')], db_index=True, default='api', help_text='API режим использует официальные API, HTML режим парсит веб-страницы', max_length=10, verbose_name='Режим парсинга')),
                ('name', models.CharField(blank=True, help_text='Опциональное название для UI', max_length=255, verbose_name='Название задачи')),
                ('config', models.JSONField(default=dict, help_text='JSON с параметрами парсинга (area, pages, technologies и т.д.)', verbose_name='Конфигурация парсинга')),
                ('config_hash', models.CharField(db_index=True, help_text='SHA256 хэш для дедупликации задач', max_length=64, verbose_name='Хэш конфигурации')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('running', 'Выполняется'), ('paused', 'Приостановлена'), ('stopped', 'Остановлена'), ('completed', 'Завершена'), ('failed', 'Ошибка')], db_index=True, default='created', max_length=20, verbose_name='Статус')),
                ('total_items', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Всего элементов')),
                ('completed_items', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Завершено элементов')),
                ('failed_items', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Элементов с ошибками')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата запуска')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приостановки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='ID основной Celery задачи-координатора', max_length=255, null=True, verbose_name='Celery Task ID')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('result_data', models.JSONField(blank=True, help_text='Итоговые данные выполнения задачи', null=True, verbose_name='Результат')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsing_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Задача парсинга',
                'verbose_name_plural': 'Задачи парсинга',
                'ordering': ['-created_at'],
                'db_table': 'vpm_parsing_task',
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_item_id', models.CharField(help_text='Например, hh_id вакансии', max_length=100, verbose_name='ID элемента на источнике')),
                ('url', models.URLField(verbose_name='URL элемента')),
                ('url_hash', models.CharField(db_index=True, help_text='SHA256 хэш для дедупликации', max_length=64, verbose_name='Хэш URL')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('in_progress', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('retrying', 'Повторная попытка'), ('blocked', 'Заблокировано')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('attempts_count', models.IntegerField(default=0, verbose_name='Количество попыток')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='Максимум попыток')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Время последней попытки')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Последняя ошибка')),
                ('last_error_type', models.CharField(blank=True, choices=[('network', 'Сетевая ошибка'), ('blocked', 'Блокировка'), ('parsing', 'Ошибка парсинга'), ('validation', 'Ошибка валидации'), ('unknown', 'Неизвестная ошибка')], max_length=20, null=True, verbose_name='Тип ошибки')),
                ('worker_id', models.CharField(blank=True, db_index=True, help_text="ID Celery worker'а, обрабатывающего элемент", max_length=255, null=True, verbose_name='Worker ID')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время захвата')),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Для crash recovery', null=True, verbose_name='Истечение lease')),
                ('result_vacancy_id', models.BigIntegerField(blank=True, help_text='FK к нормализованной Vacancy', null=True, verbose_name='ID результата')),
                ('extracted_data', models.JSONField(blank=True, help_text='Сырые данные для отладки/reprocessing', null=True, verbose_name='Извлеченные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vacancies_parser.parsingtask', verbose_name='Задача парсинга')),
            ],
            options={
                'verbose_name': 'Элемент задачи',
                'verbose_name_plural': 'Элементы задач',
                'ordering': ['id'],
                'db_table': 'vpm_task_item',
            },
        ),
        migrations.AddIndex(
            model_name='parsingtask',
            index=models.Index(fields=['source', 'status'], name='vacancies_p_source_d7e1da_idx'),
        ),
        migrations.AddIndex(
            model_name='parsingtask',
            index=models.Index(fields=['parsing_mode', 'status'], name='vacancies_p_parsing_cda97e_idx'),
        ),
        migrations.AddIndex(
            model_name='parsingtask',
            index=models.Index(fields=['created_at', 'status'], name='vacancies_p_created_b4bb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='parsingtask',
            index=models.Index(fields=['config_hash'], name='vacancies_p_config__f40985_idx'),
        ),
        migrations.AddIndex(
            model_name='parsingtask',
            index=models.Index(fields=['celery_task_id'], name='vacancies_p_celery__09f254_idx'),
        ),
        migrations.AddConstraint(
            model_name='parsingtask',
            constraint=models.CheckConstraint(condition=models.Q(('completed_items__lte', models.F('total_items'))), name='parsing_task_completed_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='parsingtask',
            constraint=models.CheckConstraint(condition=models.Q(('failed_items__lte', models.F('total_items'))), name='parsing_task_failed_lte_total'),
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['task', 'status', 'lease_expires_at'], name='vacancies_p_task_id_169847_idx'),
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['status', 'lease_expires_at'], name='vacancies_p_status_377f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['worker_id', 'status'], name='vacancies_p_worker__60ff07_idx'),
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['url_hash'], name='vacancies_p_url_has_36fadd_idx'),
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['task', 'status', 'updated_at'], name='vacancies_p_task_id_4ca246_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskitem',
            unique_together={('task', 'source_item_id')},
        ),
    ]
