# Generated by Django 5.2.8 on 2026-01-12 20:04

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_parser', '0001_create_parsing_task_and_taskitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('headhunter', 'HeadHunter'), ('habr_career', 'Habr Career'), ('superjob', 'SuperJob')], db_index=True, max_length=50, verbose_name='Источник')),
                ('source_id', models.CharField(help_text='Оригинальный ID вакансии (hh_id, habr_id, superjob_id)', max_length=100, verbose_name='ID на источнике')),
                ('source_url', models.URLField(max_length=512, verbose_name='URL вакансии на источнике')),
                ('parsing_mode', models.CharField(choices=[('api', 'API режим'), ('html', 'HTML режим')], db_index=True, help_text='Каким способом была получена вакансия', max_length=10, verbose_name='Режим парсинга')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название вакансии')),
                ('company_name', models.CharField(db_index=True, max_length=255, verbose_name='Название компании')),
                ('company_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='URL компании')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('salary_from', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(blank=True, choices=[('RUR', 'Рубли'), ('USD', 'Доллары'), ('EUR', 'Евро'), ('KZT', 'Тенге'), ('UAH', 'Гривны'), ('BYR', 'Белорусские рубли')], max_length=3, null=True, verbose_name='Валюта')),
                ('salary_gross', models.BooleanField(blank=True, help_text='True = gross (до налогов), False = net (на руки)', null=True, verbose_name='До вычета налогов')),
                ('area_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Город/регион')),
                ('area_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID города на источнике')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('experience', models.CharField(blank=True, choices=[('noExperience', 'Нет опыта'), ('between1And3', 'От 1 до 3 лет'), ('between3And6', 'От 3 до 6 лет'), ('moreThan6', 'Более 6 лет')], max_length=20, null=True, verbose_name='Требуемый опыт')),
                ('employment_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('project', 'Проектная работа'), ('volunteer', 'Волонтерство'), ('probation', 'Стажировка')], max_length=20), blank=True, null=True, size=None, verbose_name='Типы занятости')),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('fullDay', 'Полный день'), ('shift', 'Сменный график'), ('flexible', 'Гибкий график'), ('remote', 'Удаленная работа'), ('flyInFlyOut', 'Вахтовый метод')], max_length=20), blank=True, null=True, size=None, verbose_name='Графики работы')),
                ('key_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Ключевые навыки')),
                ('professional_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Профессиональные роли')),
                ('contacts', models.JSONField(blank=True, help_text='JSON с контактами (name, email, phones)', null=True, verbose_name='Контакты')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('archived', models.BooleanField(db_index=True, default=False, verbose_name='Архивная')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации на источнике')),
                ('has_test', models.BooleanField(blank=True, null=True, verbose_name='Есть тестовое задание')),
                ('accepts_handicapped', models.BooleanField(blank=True, null=True, verbose_name='Доступна для людей с ОВЗ')),
                ('response_letter_required', models.BooleanField(blank=True, null=True, verbose_name='Требуется сопроводительное письмо')),
                ('source_specific_data', models.JSONField(blank=True, default=dict, help_text='JSON с полями, уникальными для источника', verbose_name='Специфичные данные источника')),
                ('raw_data', models.JSONField(blank=True, help_text='Полный ответ от источника для отладки/reprocessing', null=True, verbose_name='Сырые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последней проверки')),
                ('version', models.IntegerField(default=1, verbose_name='Версия')),
                ('task_item', models.ForeignKey(blank=True, help_text='Связь с TaskItem для отслеживания источника парсинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_vacancies', to='vacancies_parser.taskitem', verbose_name='Элемент задачи')),
            ],
            options={
                'verbose_name': 'Нормализованная вакансия',
                'verbose_name_plural': 'Нормализованные вакансии',
                'ordering': ['-created_at'],
                'db_table': 'vpm_vacancy',
            },
        ),
        migrations.CreateModel(
            name='ParsingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('total_processed', models.IntegerField(default=0, verbose_name='Всего обработано')),
                ('successful_items', models.IntegerField(default=0, verbose_name='Успешно обработано')),
                ('failed_items', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('blocked_items', models.IntegerField(default=0, verbose_name='Заблокировано')),
                ('avg_item_duration_ms', models.FloatField(blank=True, null=True, verbose_name='Среднее время на элемент (мс)')),
                ('items_per_second', models.FloatField(blank=True, null=True, verbose_name='Элементов в секунду')),
                ('complete_records', models.IntegerField(default=0, help_text='Записи со всеми обязательными полями', verbose_name='Полных записей')),
                ('incomplete_records', models.IntegerField(default=0, verbose_name='Неполных записей')),
                ('error_breakdown', models.JSONField(default=dict, help_text='JSON: {error_type: count}', verbose_name='Разбивка ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='vacancies_parser.parsingtask', verbose_name='Задача парсинга')),
            ],
            options={
                'verbose_name': 'Статистика парсинга',
                'verbose_name_plural': 'Статистика парсинга',
                'ordering': ['-created_at'],
                'db_table': 'vpm_parsing_statistics',
            },
        ),
        migrations.CreateModel(
            name='VacancyChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Версия')),
                ('changed_fields', models.JSONField(help_text='JSON с diff: {field: {old: value, new: value}}', verbose_name='Измененные поля')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата изменения')),
                ('parsing_mode', models.CharField(choices=[('api', 'API режим'), ('html', 'HTML режим')], max_length=10, verbose_name='Режим парсинга')),
                ('task_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy_changes', to='vacancies_parser.taskitem', verbose_name='Элемент задачи')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='vacancies_parser.normalizedvacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'История изменений вакансии',
                'verbose_name_plural': 'История изменений вакансий',
                'ordering': ['-changed_at'],
                'db_table': 'vpm_vacancy_change_history',
            },
        ),
        migrations.AddIndex(
            model_name='normalizedvacancy',
            index=models.Index(fields=['source', 'is_active'], name='vacancies_p_source_481cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedvacancy',
            index=models.Index(fields=['source', 'archived'], name='vacancies_p_source_db3441_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedvacancy',
            index=models.Index(fields=['company_name', 'is_active'], name='vacancies_p_company_429fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedvacancy',
            index=models.Index(fields=['area_name', 'is_active'], name='vacancies_p_area_na_57b866_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedvacancy',
            index=models.Index(fields=['parsing_mode', 'created_at'], name='vacancies_p_parsing_de1840_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedvacancy',
            index=models.Index(fields=['published_at', 'is_active'], name='vacancies_p_publish_dd9e41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='normalizedvacancy',
            unique_together={('source', 'source_id')},
        ),
        migrations.AddIndex(
            model_name='parsingstatistics',
            index=models.Index(fields=['task', 'created_at'], name='vacancies_p_task_id_3ff93f_idx'),
        ),
        migrations.AddIndex(
            model_name='parsingstatistics',
            index=models.Index(fields=['started_at'], name='vacancies_p_started_8c9a02_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancychangehistory',
            index=models.Index(fields=['vacancy', 'changed_at'], name='vacancies_p_vacancy_110ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancychangehistory',
            index=models.Index(fields=['changed_at'], name='vacancies_p_changed_e780ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancychangehistory',
            unique_together={('vacancy', 'version')},
        ),
    ]
