# Generated by Django 5.2.8 on 2026-01-19 10:36

from django.conf import settings
from django.db import migrations, models, connection


def rename_tables_if_needed(apps, schema_editor):
    """
    Условное переименование таблиц: переименовывает только если таблицы
    со старыми именами существуют. Это нужно для случаев, когда миграции
    0001-0003 уже были применены и таблицы созданы со старыми именами.
    """
    with connection.cursor() as cursor:
        # Маппинг старых имен на новые
        table_mappings = {
            'vacancies_parser_parsingtask': 'vpm_parsing_task',
            'vacancies_parser_taskitem': 'vpm_task_item',
            'vacancies_parser_normalizedvacancy': 'vpm_vacancy',
            'vacancies_parser_parsingstatistics': 'vpm_parsing_statistics',
            'vacancies_parser_vacancychangehistory': 'vpm_vacancy_change_history',
        }
        
        for old_name, new_name in table_mappings.items():
            # Проверяем, существует ли таблица со старым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [old_name])
            
            old_exists = cursor.fetchone()[0]
            
            # Проверяем, существует ли таблица с новым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [new_name])
            
            new_exists = cursor.fetchone()[0]
            
            # Переименовываем только если старая таблица существует, а новая - нет
            if old_exists and not new_exists:
                cursor.execute(f'ALTER TABLE "{old_name}" RENAME TO "{new_name}";')
                print(f"[INFO] Таблица {old_name} переименована в {new_name}")
            elif new_exists:
                print(f"[INFO] Таблица {new_name} уже существует, переименование не требуется")
            else:
                print(f"[INFO] Таблица {old_name} не существует, переименование не требуется")


def rename_indexes_if_needed(apps, schema_editor):
    """
    Условное переименование индексов: переименовывает только если индексы
    со старыми именами существуют.
    """
    with connection.cursor() as cursor:
        # Маппинг старых имен индексов на новые
        index_mappings = [
            # NormalizedVacancy
            ('vacancies_p_source_481cc1_idx', 'vpm_vacancy_source_8ad0fd_idx', 'vpm_vacancy'),
            ('vacancies_p_source_db3441_idx', 'vpm_vacancy_source_da03f7_idx', 'vpm_vacancy'),
            ('vacancies_p_company_429fd0_idx', 'vpm_vacancy_company_aafde7_idx', 'vpm_vacancy'),
            ('vacancies_p_area_na_57b866_idx', 'vpm_vacancy_area_na_408fdc_idx', 'vpm_vacancy'),
            ('vacancies_p_parsing_de1840_idx', 'vpm_vacancy_parsing_8c52e6_idx', 'vpm_vacancy'),
            ('vacancies_p_publish_dd9e41_idx', 'vpm_vacancy_publish_f0e151_idx', 'vpm_vacancy'),
            # ParsingStatistics
            ('vacancies_p_task_id_3ff93f_idx', 'vpm_parsing_task_id_5414c2_idx', 'vpm_parsing_statistics'),
            ('vacancies_p_started_8c9a02_idx', 'vpm_parsing_started_0cc7c5_idx', 'vpm_parsing_statistics'),
            # ParsingTask
            ('vacancies_p_source_d7e1da_idx', 'vpm_parsing_source_ead80b_idx', 'vpm_parsing_task'),
            ('vacancies_p_parsing_cda97e_idx', 'vpm_parsing_parsing_70b423_idx', 'vpm_parsing_task'),
            ('vacancies_p_created_b4bb9c_idx', 'vpm_parsing_created_112f33_idx', 'vpm_parsing_task'),
            ('vacancies_p_config__f40985_idx', 'vpm_parsing_config__fcd57b_idx', 'vpm_parsing_task'),
            ('vacancies_p_celery__09f254_idx', 'vpm_parsing_celery__2f10bc_idx', 'vpm_parsing_task'),
            # TaskItem
            ('vacancies_p_task_id_169847_idx', 'vpm_task_it_task_id_ac9bde_idx', 'vpm_task_item'),
            ('vacancies_p_status_377f8e_idx', 'vpm_task_it_status_87928a_idx', 'vpm_task_item'),
            ('vacancies_p_worker__60ff07_idx', 'vpm_task_it_worker__ba6875_idx', 'vpm_task_item'),
            ('vacancies_p_url_has_36fadd_idx', 'vpm_task_it_url_has_cfcc72_idx', 'vpm_task_item'),
            ('vacancies_p_task_id_4ca246_idx', 'vpm_task_it_task_id_f6be21_idx', 'vpm_task_item'),
            # VacancyChangeHistory
            ('vacancies_p_vacancy_110ec2_idx', 'vpm_vacancy_vacancy_68621a_idx', 'vpm_vacancy_change_history'),
            ('vacancies_p_changed_e780ab_idx', 'vpm_vacancy_changed_d90abe_idx', 'vpm_vacancy_change_history'),
        ]
        
        for old_name, new_name, table_name in index_mappings:
            # Проверяем, существует ли индекс со старым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = %s
                );
            """, [old_name])
            
            old_exists = cursor.fetchone()[0]
            
            # Проверяем, существует ли индекс с новым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = %s
                );
            """, [new_name])
            
            new_exists = cursor.fetchone()[0]
            
            # Переименовываем только если старый индекс существует, а новый - нет
            if old_exists and not new_exists:
                cursor.execute(f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";')
                print(f"[INFO] Индекс {old_name} переименован в {new_name}")
            elif new_exists:
                print(f"[INFO] Индекс {new_name} уже существует, переименование не требуется")
            else:
                print(f"[INFO] Индекс {old_name} не существует, переименование не требуется")


def remove_duplicate_tasks(apps, schema_editor):
    """
    Удаление дубликатов задач перед созданием UniqueConstraint.
    Оставляет только самую новую задачу для каждой комбинации (source, config_hash).
    """
    with connection.cursor() as cursor:
        # Определяем имя таблицы (может быть старое или новое)
        table_name = None
        for possible_name in ['vpm_parsing_task', 'vacancies_parser_parsingtask']:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [possible_name])
            if cursor.fetchone()[0]:
                table_name = possible_name
                break
        
        if not table_name:
            print("[INFO] Таблица ParsingTask не найдена, пропускаем удаление дубликатов")
            return
        
        # Определяем имя таблицы TaskItem
        task_item_table = None
        for possible_name in ['vpm_task_item', 'vacancies_parser_taskitem']:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [possible_name])
            if cursor.fetchone()[0]:
                task_item_table = possible_name
                break
        
        # Находим дубликаты
        cursor.execute(f"""
            SELECT source, config_hash, COUNT(*) as cnt
            FROM "{table_name}"
            GROUP BY source, config_hash
            HAVING COUNT(*) > 1
        """)
        
        duplicates = cursor.fetchall()
        
        if not duplicates:
            print("[INFO] Дубликатов задач не найдено")
            return
        
        print(f"[INFO] Найдено {len(duplicates)} групп дубликатов")
        
        # Для каждой группы дубликатов оставляем только самую новую задачу
        for source, config_hash, count in duplicates:
            cursor.execute(f"""
                SELECT id 
                FROM "{table_name}"
                WHERE source = %s AND config_hash = %s
                ORDER BY created_at DESC
            """, [source, config_hash])
            
            task_ids = [row[0] for row in cursor.fetchall()]
            
            if len(task_ids) > 1:
                # Оставляем первую (самую новую), удаляем остальные
                ids_to_delete = task_ids[1:]
                
                # Сначала удаляем связанные TaskItems (если таблица существует)
                if task_item_table:
                    cursor.execute(f"""
                        DELETE FROM "{task_item_table}"
                        WHERE task_id = ANY(%s)
                    """, [ids_to_delete])
                
                # Затем удаляем сами задачи
                cursor.execute(f"""
                    DELETE FROM "{table_name}"
                    WHERE id = ANY(%s)
                """, [ids_to_delete])
                
                print(f"[INFO] Удалено {len(ids_to_delete)} дубликатов для (source={source}, config_hash={config_hash[:16]}...)")
                print(f"[INFO] Оставлена задача id={task_ids[0]}")
        
        # Обрабатываем отложенные события триггеров перед созданием constraint
        # Это необходимо для PostgreSQL, чтобы избежать ошибки "нельзя выполнить ALTER TABLE, так как с этим объектом связаны отложенные события триггеров"
        cursor.execute("SET CONSTRAINTS ALL IMMEDIATE;")
        print("[INFO] Все отложенные ограничения установлены в IMMEDIATE режим")


def remove_constraints_if_exist(apps, schema_editor):
    """
    Условное удаление constraints: удаляет только если они существуют.
    """
    with connection.cursor() as cursor:
        constraint_names = [
            'parsing_task_completed_lte_total',
            'parsing_task_failed_lte_total',
        ]
        
        for constraint_name in constraint_names:
            # Проверяем, существует ли constraint
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM pg_constraint 
                    WHERE conname = %s
                );
            """, [constraint_name])
            
            if cursor.fetchone()[0]:
                # Находим таблицу, к которой привязан constraint
                cursor.execute("""
                    SELECT conrelid::regclass::text
                    FROM pg_constraint 
                    WHERE conname = %s
                """, [constraint_name])
                
                result = cursor.fetchone()
                if result:
                    table_name = result[0]
                    cursor.execute(f'ALTER TABLE "{table_name}" DROP CONSTRAINT IF EXISTS "{constraint_name}";')
                    print(f"[INFO] Constraint {constraint_name} удален из таблицы {table_name}")
            else:
                print(f"[INFO] Constraint {constraint_name} не существует, удаление не требуется")


def reverse_rename_tables(apps, schema_editor):
    """
    Обратное переименование (для rollback).
    """
    with connection.cursor() as cursor:
        # Обратный маппинг
        table_mappings = {
            'vpm_parsing_task': 'vacancies_parser_parsingtask',
            'vpm_task_item': 'vacancies_parser_taskitem',
            'vpm_vacancy': 'vacancies_parser_normalizedvacancy',
            'vpm_parsing_statistics': 'vacancies_parser_parsingstatistics',
            'vpm_vacancy_change_history': 'vacancies_parser_vacancychangehistory',
        }
        
        for new_name, old_name in table_mappings.items():
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [new_name])
            
            if cursor.fetchone()[0]:
                cursor.execute(f'ALTER TABLE "{new_name}" RENAME TO "{old_name}";')
                print(f"[INFO] Таблица {new_name} переименована обратно в {old_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_parser', '0003_populate_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Условное переименование таблиц (если они еще не переименованы)
        migrations.RunPython(rename_tables_if_needed, reverse_rename_tables),
        # Обновляем только метаданные моделей (без переименования в БД, так как уже переименовано через RunPython)
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Ничего не делаем в БД, так как уже переименовано
            state_operations=[
                migrations.AlterModelTable(
                    name='parsingtask',
                    table='vpm_parsing_task',
                ),
                migrations.AlterModelTable(
                    name='taskitem',
                    table='vpm_task_item',
                ),
                migrations.AlterModelTable(
                    name='normalizedvacancy',
                    table='vpm_vacancy',
                ),
                migrations.AlterModelTable(
                    name='parsingstatistics',
                    table='vpm_parsing_statistics',
                ),
                migrations.AlterModelTable(
                    name='vacancychangehistory',
                    table='vpm_vacancy_change_history',
                ),
            ],
        ),
        # Условное удаление constraints (если они существуют)
        migrations.RunPython(remove_constraints_if_exist, migrations.RunPython.noop),
        # Обновляем метаданные (без удаления в БД, так как уже удалено через RunPython)
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Ничего не делаем в БД, так как уже удалено
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='parsingtask',
                    name='parsing_task_completed_lte_total',
                ),
                migrations.RemoveConstraint(
                    model_name='parsingtask',
                    name='parsing_task_failed_lte_total',
                ),
            ],
        ),
        # Условное переименование индексов (если они еще не переименованы)
        migrations.RunPython(rename_indexes_if_needed, migrations.RunPython.noop),
        # Обновляем метаданные индексов (без переименования в БД, так как уже переименовано через RunPython)
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Ничего не делаем в БД, так как уже переименовано
            state_operations=[
                migrations.RenameIndex(
                    model_name='normalizedvacancy',
                    new_name='vpm_vacancy_source_8ad0fd_idx',
                    old_name='vacancies_p_source_481cc1_idx',
                ),
                migrations.RenameIndex(
                    model_name='normalizedvacancy',
                    new_name='vpm_vacancy_source_da03f7_idx',
                    old_name='vacancies_p_source_db3441_idx',
                ),
                migrations.RenameIndex(
                    model_name='normalizedvacancy',
                    new_name='vpm_vacancy_company_aafde7_idx',
                    old_name='vacancies_p_company_429fd0_idx',
                ),
                migrations.RenameIndex(
                    model_name='normalizedvacancy',
                    new_name='vpm_vacancy_area_na_408fdc_idx',
                    old_name='vacancies_p_area_na_57b866_idx',
                ),
                migrations.RenameIndex(
                    model_name='normalizedvacancy',
                    new_name='vpm_vacancy_parsing_8c52e6_idx',
                    old_name='vacancies_p_parsing_de1840_idx',
                ),
                migrations.RenameIndex(
                    model_name='normalizedvacancy',
                    new_name='vpm_vacancy_publish_f0e151_idx',
                    old_name='vacancies_p_publish_dd9e41_idx',
                ),
                migrations.RenameIndex(
                    model_name='parsingstatistics',
                    new_name='vpm_parsing_task_id_5414c2_idx',
                    old_name='vacancies_p_task_id_3ff93f_idx',
                ),
                migrations.RenameIndex(
                    model_name='parsingstatistics',
                    new_name='vpm_parsing_started_0cc7c5_idx',
                    old_name='vacancies_p_started_8c9a02_idx',
                ),
                migrations.RenameIndex(
                    model_name='parsingtask',
                    new_name='vpm_parsing_source_ead80b_idx',
                    old_name='vacancies_p_source_d7e1da_idx',
                ),
                migrations.RenameIndex(
                    model_name='parsingtask',
                    new_name='vpm_parsing_parsing_70b423_idx',
                    old_name='vacancies_p_parsing_cda97e_idx',
                ),
                migrations.RenameIndex(
                    model_name='parsingtask',
                    new_name='vpm_parsing_created_112f33_idx',
                    old_name='vacancies_p_created_b4bb9c_idx',
                ),
                migrations.RenameIndex(
                    model_name='parsingtask',
                    new_name='vpm_parsing_config__fcd57b_idx',
                    old_name='vacancies_p_config__f40985_idx',
                ),
                migrations.RenameIndex(
                    model_name='parsingtask',
                    new_name='vpm_parsing_celery__2f10bc_idx',
                    old_name='vacancies_p_celery__09f254_idx',
                ),
                migrations.RenameIndex(
                    model_name='taskitem',
                    new_name='vpm_task_it_task_id_ac9bde_idx',
                    old_name='vacancies_p_task_id_169847_idx',
                ),
                migrations.RenameIndex(
                    model_name='taskitem',
                    new_name='vpm_task_it_status_87928a_idx',
                    old_name='vacancies_p_status_377f8e_idx',
                ),
                migrations.RenameIndex(
                    model_name='taskitem',
                    new_name='vpm_task_it_worker__ba6875_idx',
                    old_name='vacancies_p_worker__60ff07_idx',
                ),
                migrations.RenameIndex(
                    model_name='taskitem',
                    new_name='vpm_task_it_url_has_cfcc72_idx',
                    old_name='vacancies_p_url_has_36fadd_idx',
                ),
                migrations.RenameIndex(
                    model_name='taskitem',
                    new_name='vpm_task_it_task_id_f6be21_idx',
                    old_name='vacancies_p_task_id_4ca246_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancychangehistory',
                    new_name='vpm_vacancy_vacancy_68621a_idx',
                    old_name='vacancies_p_vacancy_110ec2_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancychangehistory',
                    new_name='vpm_vacancy_changed_d90abe_idx',
                    old_name='vacancies_p_changed_e780ab_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='normalizedvacancy',
            name='deduplication_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Агрегированный хэш ключевых полей для поиска дубликатов', max_length=64, verbose_name='Хэш для дедупликации'),
        ),
        migrations.AddField(
            model_name='normalizedvacancy',
            name='deduplication_status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('original', 'Оригинал'), ('duplicate', 'Дубликат')], db_index=True, default='pending', max_length=20, verbose_name='Статус дедупликации'),
        ),
        migrations.AddField(
            model_name='normalizedvacancy',
            name='original_vacancy_id',
            field=models.IntegerField(blank=True, help_text='FK на NormalizedVacancy, если это дубликат', null=True, verbose_name='ID оригинальной вакансии'),
        ),
        migrations.AddIndex(
            model_name='normalizedvacancy',
            index=models.Index(fields=['title', 'company_name'], name='vpm_vacancy_title_011bec_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedvacancy',
            index=models.Index(fields=['title', 'area_name'], name='vpm_vacancy_title_beea68_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedvacancy',
            index=models.Index(fields=['salary_from', 'salary_to'], name='vpm_vacancy_salary__edfbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedvacancy',
            index=models.Index(fields=['deduplication_hash'], name='vpm_vacancy_dedupli_0a54f2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['task', 'source_item_id'], name='vpm_task_it_task_id_20bae1_idx'),
        ),
        migrations.AddConstraint(
            model_name='parsingtask',
            constraint=models.CheckConstraint(condition=models.Q(('completed_items__lte', models.F('total_items'))), name='vpm_parsing_task_completed_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='parsingtask',
            constraint=models.CheckConstraint(condition=models.Q(('failed_items__lte', models.F('total_items'))), name='vpm_parsing_task_failed_lte_total'),
        ),
        # Удаление дубликатов перед созданием UniqueConstraint
        migrations.RunPython(remove_duplicate_tasks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='parsingtask',
            constraint=models.UniqueConstraint(fields=('source', 'config_hash'), name='vpm_parsing_task_unique_config'),
        ),
    ]
