# Generated by Django 5.2.8 on 2026-03-16 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_parser', '0004_remove_parsingtask_parsing_task_completed_lte_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('endpoint', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('event_type', models.CharField(choices=[('timeout', 'Timeout'), ('http_429', 'HTTP 429'), ('error', 'Error')], db_index=True, max_length=20)),
                ('count', models.IntegerField(default=1)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Событие внешнего API',
                'verbose_name_plural': 'События внешнего API',
                'indexes': [models.Index(fields=['source', 'event_type', 'created_at'], name='vacancies_p_source_49fbb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('parsing_task_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успех'), ('failure', 'Ошибка')], db_index=True, default='running', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed', models.IntegerField(default=0)),
                ('saved', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('http_429', models.IntegerField(default=0)),
                ('retries', models.IntegerField(default=0)),
                ('kwargs_digest', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Запуск задачи (TaskRun)',
                'verbose_name_plural': 'Запуски задач (TaskRun)',
                'indexes': [models.Index(fields=['task_name', 'status', 'started_at'], name='vacancies_p_task_na_db0dae_idx'), models.Index(fields=['source', 'status', 'started_at'], name='vacancies_p_source_133c8a_idx')],
            },
        ),
    ]
