# Generated by Django 5.2.8 on 2026-01-19 10:42

from django.db import migrations, models, connection


def rename_tables_if_needed(apps, schema_editor):
    """
    Условное переименование таблиц: переименовывает только если таблицы
    со старыми именами существуют.
    """
    with connection.cursor() as cursor:
        # Маппинг старых имен на новые
        table_mappings = {
            'vacancies_parser_superjob_superjobvacancy': 'vpm_sj_vacancy',
            'vacancies_parser_superjob_superjobvacancyversion': 'vpm_sj_vacancy_version',
            'vacancies_parser_superjob_superjobvacancychangehistory': 'vpm_sj_vacancy_change_history',
        }
        
        for old_name, new_name in table_mappings.items():
            # Проверяем, существует ли таблица со старым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [old_name])
            
            old_exists = cursor.fetchone()[0]
            
            # Проверяем, существует ли таблица с новым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [new_name])
            
            new_exists = cursor.fetchone()[0]
            
            # Переименовываем только если старая таблица существует, а новая - нет
            if old_exists and not new_exists:
                cursor.execute(f'ALTER TABLE "{old_name}" RENAME TO "{new_name}";')
                print(f"[INFO] Таблица {old_name} переименована в {new_name}")
            elif new_exists:
                print(f"[INFO] Таблица {new_name} уже существует, переименование не требуется")
            else:
                print(f"[INFO] Таблица {old_name} не существует, переименование не требуется")


def rename_indexes_if_needed(apps, schema_editor):
    """
    Условное переименование индексов: переименовывает только если индексы
    со старыми именами существуют.
    """
    with connection.cursor() as cursor:
        # Маппинг старых имен индексов на новые (из миграции 0001)
        index_mappings = [
            ('vacancies_p_title_cd8ce7_idx', 'vpm_sj_vaca_title_cd8ce7_idx'),
            ('vacancies_p_company_3fd3b5_idx', 'vpm_sj_vaca_company_3fd3b5_idx'),
            ('vacancies_p_city_6a5a90_idx', 'vpm_sj_vaca_city_6a5a90_idx'),
            ('vacancies_p_publish_48800a_idx', 'vpm_sj_vaca_publish_48800a_idx'),
            ('vacancies_p_superjo_65b74d_idx', 'vpm_sj_vaca_superjo_65b74d_idx'),
            ('vacancies_p_employe_bf3c34_idx', 'vpm_sj_vaca_employe_bf3c34_idx'),
            ('vacancies_p_current_74ba20_idx', 'vpm_sj_vaca_current_74ba20_idx'),
            ('vacancies_p_vacancy_4d599c_idx', 'vpm_sj_vaca_vacancy_4d599c_idx'),
            ('vacancies_p_created_447215_idx', 'vpm_sj_vaca_created_447215_idx'),
            ('vacancies_p_vacancy_5f7612_idx', 'vpm_sj_vaca_vacancy_5f7612_idx'),
            ('vacancies_p_field_n_4da4cd_idx', 'vpm_sj_vaca_field_n_4da4cd_idx'),
        ]
        
        for old_name, new_name in index_mappings:
            # Проверяем, существует ли индекс со старым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = %s
                );
            """, [old_name])
            
            old_exists = cursor.fetchone()[0]
            
            # Проверяем, существует ли индекс с новым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = %s
                );
            """, [new_name])
            
            new_exists = cursor.fetchone()[0]
            
            # Переименовываем только если старый индекс существует, а новый - нет
            if old_exists and not new_exists:
                cursor.execute(f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";')
                print(f"[INFO] Индекс {old_name} переименован в {new_name}")
            elif new_exists:
                print(f"[INFO] Индекс {new_name} уже существует, переименование не требуется")
            else:
                print(f"[INFO] Индекс {old_name} не существует, переименование не требуется")


def reverse_rename_tables(apps, schema_editor):
    """
    Обратное переименование (для rollback).
    """
    with connection.cursor() as cursor:
        table_mappings = {
            'vpm_sj_vacancy': 'vacancies_parser_superjob_superjobvacancy',
            'vpm_sj_vacancy_version': 'vacancies_parser_superjob_superjobvacancyversion',
            'vpm_sj_vacancy_change_history': 'vacancies_parser_superjob_superjobvacancychangehistory',
        }
        
        for new_name, old_name in table_mappings.items():
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [new_name])
            
            if cursor.fetchone()[0]:
                cursor.execute(f'ALTER TABLE "{new_name}" RENAME TO "{old_name}";')
                print(f"[INFO] Таблица {new_name} переименована обратно в {old_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_parser_superjob', '0001_initial'),
    ]

    operations = [
        # Условное переименование таблиц (если они еще не переименованы)
        migrations.RunPython(rename_tables_if_needed, reverse_rename_tables),
        # Обновляем только метаданные моделей (без переименования в БД)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='superjobvacancy',
                    table='vpm_sj_vacancy',
                ),
                migrations.AlterModelTable(
                    name='superjobvacancychangehistory',
                    table='vpm_sj_vacancy_change_history',
                ),
                migrations.AlterModelTable(
                    name='superjobvacancyversion',
                    table='vpm_sj_vacancy_version',
                ),
            ],
        ),
        # Условное переименование индексов (если они еще не переименованы)
        migrations.RunPython(rename_indexes_if_needed, migrations.RunPython.noop),
        # Обновляем метаданные индексов (без переименования в БД)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='superjobvacancy',
                    new_name='vpm_sj_vaca_title_cd8ce7_idx',
                    old_name='vacancies_p_title_cd8ce7_idx',
                ),
                migrations.RenameIndex(
                    model_name='superjobvacancy',
                    new_name='vpm_sj_vaca_company_3fd3b5_idx',
                    old_name='vacancies_p_company_3fd3b5_idx',
                ),
                migrations.RenameIndex(
                    model_name='superjobvacancy',
                    new_name='vpm_sj_vaca_city_6a5a90_idx',
                    old_name='vacancies_p_city_6a5a90_idx',
                ),
                migrations.RenameIndex(
                    model_name='superjobvacancy',
                    new_name='vpm_sj_vaca_publish_48800a_idx',
                    old_name='vacancies_p_publish_48800a_idx',
                ),
                migrations.RenameIndex(
                    model_name='superjobvacancy',
                    new_name='vpm_sj_vaca_superjo_65b74d_idx',
                    old_name='vacancies_p_superjo_65b74d_idx',
                ),
                migrations.RenameIndex(
                    model_name='superjobvacancy',
                    new_name='vpm_sj_vaca_employe_bf3c34_idx',
                    old_name='vacancies_p_employe_bf3c34_idx',
                ),
                migrations.RenameIndex(
                    model_name='superjobvacancy',
                    new_name='vpm_sj_vaca_current_74ba20_idx',
                    old_name='vacancies_p_current_74ba20_idx',
                ),
                migrations.RenameIndex(
                    model_name='superjobvacancyversion',
                    new_name='vpm_sj_vaca_vacancy_4d599c_idx',
                    old_name='vacancies_p_vacancy_4d599c_idx',
                ),
                migrations.RenameIndex(
                    model_name='superjobvacancyversion',
                    new_name='vpm_sj_vaca_created_447215_idx',
                    old_name='vacancies_p_created_447215_idx',
                ),
                migrations.RenameIndex(
                    model_name='superjobvacancychangehistory',
                    new_name='vpm_sj_vaca_vacancy_5f7612_idx',
                    old_name='vacancies_p_vacancy_5f7612_idx',
                ),
                migrations.RenameIndex(
                    model_name='superjobvacancychangehistory',
                    new_name='vpm_sj_vaca_field_n_4da4cd_idx',
                    old_name='vacancies_p_field_n_4da4cd_idx',
                ),
            ],
        ),
    ]
