# Generated by Django 5.2.8 on 2026-01-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_parser_superjob', '0002_rename_tables_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='superjobvacancy',
            new_name='vpm_sj_vaca_title_f3a4af_idx',
            old_name='vpm_sj_vaca_title_cd8ce7_idx',
        ),
        migrations.RenameIndex(
            model_name='superjobvacancy',
            new_name='vpm_sj_vaca_company_32050e_idx',
            old_name='vpm_sj_vaca_company_3fd3b5_idx',
        ),
        migrations.RenameIndex(
            model_name='superjobvacancy',
            new_name='vpm_sj_vaca_city_87811a_idx',
            old_name='vpm_sj_vaca_city_6a5a90_idx',
        ),
        migrations.RenameIndex(
            model_name='superjobvacancy',
            new_name='vpm_sj_vaca_publish_7499aa_idx',
            old_name='vpm_sj_vaca_publish_48800a_idx',
        ),
        migrations.RenameIndex(
            model_name='superjobvacancy',
            new_name='vpm_sj_vaca_superjo_eaef6a_idx',
            old_name='vpm_sj_vaca_superjo_65b74d_idx',
        ),
        migrations.RenameIndex(
            model_name='superjobvacancy',
            new_name='vpm_sj_vaca_employe_514a44_idx',
            old_name='vpm_sj_vaca_employe_bf3c34_idx',
        ),
        migrations.RenameIndex(
            model_name='superjobvacancy',
            new_name='vpm_sj_vaca_current_d98028_idx',
            old_name='vpm_sj_vaca_current_74ba20_idx',
        ),
        migrations.RenameIndex(
            model_name='superjobvacancychangehistory',
            new_name='vpm_sj_vaca_vacancy_fc8e0a_idx',
            old_name='vpm_sj_vaca_vacancy_5f7612_idx',
        ),
        migrations.RenameIndex(
            model_name='superjobvacancychangehistory',
            new_name='vpm_sj_vaca_field_n_f6924c_idx',
            old_name='vpm_sj_vaca_field_n_4da4cd_idx',
        ),
        migrations.RenameIndex(
            model_name='superjobvacancyversion',
            new_name='vpm_sj_vaca_vacancy_5c4eda_idx',
            old_name='vpm_sj_vaca_vacancy_4d599c_idx',
        ),
        migrations.RenameIndex(
            model_name='superjobvacancyversion',
            new_name='vpm_sj_vaca_created_83a34b_idx',
            old_name='vpm_sj_vaca_created_447215_idx',
        ),
    ]
