# Generated by Django 5.2.8 on 2026-01-19 10:42

from django.db import migrations, models, connection


def rename_tables_if_needed(apps, schema_editor):
    """
    Условное переименование таблиц: переименовывает только если таблицы
    со старыми именами существуют.
    """
    with connection.cursor() as cursor:
        # Маппинг старых имен на новые
        table_mappings = {
            'vacancies_parser_headhunter_vacancy': 'vpm_hh_vacancy',
            'vacancies_parser_headhunter_vacancyversion': 'vpm_hh_vacancy_version',
            'vacancies_parser_headhunter_vacancychangehistory': 'vpm_hh_vacancy_change_history',
        }
        
        for old_name, new_name in table_mappings.items():
            # Проверяем, существует ли таблица со старым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [old_name])
            
            old_exists = cursor.fetchone()[0]
            
            # Проверяем, существует ли таблица с новым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [new_name])
            
            new_exists = cursor.fetchone()[0]
            
            # Переименовываем только если старая таблица существует, а новая - нет
            if old_exists and not new_exists:
                cursor.execute(f'ALTER TABLE "{old_name}" RENAME TO "{new_name}";')
                print(f"[INFO] Таблица {old_name} переименована в {new_name}")
            elif new_exists:
                print(f"[INFO] Таблица {new_name} уже существует, переименование не требуется")
            else:
                print(f"[INFO] Таблица {old_name} не существует, переименование не требуется")


def rename_indexes_if_needed(apps, schema_editor):
    """
    Условное переименование индексов: переименовывает только если индексы
    со старыми именами существуют.
    """
    with connection.cursor() as cursor:
        # Маппинг старых имен индексов на новые
        index_mappings = [
            ('vacancies_p_title_58635d_idx', 'vpm_hh_vaca_title_a3cbf2_idx'),
            ('vacancies_p_company_d90742_idx', 'vpm_hh_vaca_company_4a7186_idx'),
            ('vacancies_p_city_176a9d_idx', 'vpm_hh_vaca_city_e8825f_idx'),
            ('vacancies_p_publish_b8da66_idx', 'vpm_hh_vaca_publish_5b6424_idx'),
            ('vacancies_p_hh_id_4207eb_idx', 'vpm_hh_vaca_hh_id_992cbd_idx'),
            ('vacancies_p_employe_d56dd6_idx', 'vpm_hh_vaca_employe_40b2e2_idx'),
            ('vacancies_p_current_ce01b8_idx', 'vpm_hh_vaca_current_3b563e_idx'),
            ('vacancies_p_vacancy_a33263_idx', 'vpm_hh_vaca_vacancy_153dc7_idx'),
            ('vacancies_p_field_n_a5a6a6_idx', 'vpm_hh_vaca_field_n_d91e80_idx'),
            ('vacancies_p_created_65b063_idx', 'vpm_hh_vaca_created_1787fb_idx'),
            ('vacancies_p_vacancy_51a7df_idx', 'vpm_hh_vaca_vacancy_1f4763_idx'),
            ('vacancies_p_created_8c9ac7_idx', 'vpm_hh_vaca_created_7dbb4d_idx'),
        ]
        
        for old_name, new_name in index_mappings:
            # Проверяем, существует ли индекс со старым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = %s
                );
            """, [old_name])
            
            old_exists = cursor.fetchone()[0]
            
            # Проверяем, существует ли индекс с новым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = %s
                );
            """, [new_name])
            
            new_exists = cursor.fetchone()[0]
            
            # Переименовываем только если старый индекс существует, а новый - нет
            if old_exists and not new_exists:
                cursor.execute(f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";')
                print(f"[INFO] Индекс {old_name} переименован в {new_name}")
            elif new_exists:
                print(f"[INFO] Индекс {new_name} уже существует, переименование не требуется")
            else:
                print(f"[INFO] Индекс {old_name} не существует, переименование не требуется")


def reverse_rename_tables(apps, schema_editor):
    """
    Обратное переименование (для rollback).
    """
    with connection.cursor() as cursor:
        table_mappings = {
            'vpm_hh_vacancy': 'vacancies_parser_headhunter_vacancy',
            'vpm_hh_vacancy_version': 'vacancies_parser_headhunter_vacancyversion',
            'vpm_hh_vacancy_change_history': 'vacancies_parser_headhunter_vacancychangehistory',
        }
        
        for new_name, old_name in table_mappings.items():
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [new_name])
            
            if cursor.fetchone()[0]:
                cursor.execute(f'ALTER TABLE "{new_name}" RENAME TO "{old_name}";')
                print(f"[INFO] Таблица {new_name} переименована обратно в {old_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_parser_headhunter', '0004_alter_vacancy_salary_gross'),
    ]

    operations = [
        # Условное переименование таблиц (если они еще не переименованы)
        migrations.RunPython(rename_tables_if_needed, reverse_rename_tables),
        # Обновляем только метаданные моделей (без переименования в БД)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='vacancy',
                    table='vpm_hh_vacancy',
                ),
                migrations.AlterModelTable(
                    name='vacancychangehistory',
                    table='vpm_hh_vacancy_change_history',
                ),
                migrations.AlterModelTable(
                    name='vacancyversion',
                    table='vpm_hh_vacancy_version',
                ),
            ],
        ),
        # Условное переименование индексов (если они еще не переименованы)
        migrations.RunPython(rename_indexes_if_needed, migrations.RunPython.noop),
        # Обновляем метаданные индексов (без переименования в БД)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hh_vaca_title_a3cbf2_idx',
                    old_name='vacancies_p_title_58635d_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hh_vaca_company_4a7186_idx',
                    old_name='vacancies_p_company_d90742_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hh_vaca_city_e8825f_idx',
                    old_name='vacancies_p_city_176a9d_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hh_vaca_publish_5b6424_idx',
                    old_name='vacancies_p_publish_b8da66_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hh_vaca_hh_id_992cbd_idx',
                    old_name='vacancies_p_hh_id_4207eb_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hh_vaca_employe_40b2e2_idx',
                    old_name='vacancies_p_employe_d56dd6_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hh_vaca_current_3b563e_idx',
                    old_name='vacancies_p_current_ce01b8_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancychangehistory',
                    new_name='vpm_hh_vaca_vacancy_153dc7_idx',
                    old_name='vacancies_p_vacancy_a33263_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancychangehistory',
                    new_name='vpm_hh_vaca_field_n_d91e80_idx',
                    old_name='vacancies_p_field_n_a5a6a6_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancychangehistory',
                    new_name='vpm_hh_vaca_created_1787fb_idx',
                    old_name='vacancies_p_created_65b063_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancyversion',
                    new_name='vpm_hh_vaca_vacancy_1f4763_idx',
                    old_name='vacancies_p_vacancy_51a7df_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancyversion',
                    new_name='vpm_hh_vaca_created_7dbb4d_idx',
                    old_name='vacancies_p_created_8c9ac7_idx',
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['title', 'city'], name='vpm_hh_vaca_title_aecd62_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['salary_from', 'salary_to'], name='vpm_hh_vaca_salary__10321e_idx'),
        ),
    ]
